### ISSUE TITLE
Using Debian 10 with backports keep not reading the external disk

### ISSUE THREAD

**Issue by linuxitomio** [flathub/org.gnome.Lollypop#128] opened 2021-01-18 11:16 UTC
How can I install Lollypop if I dont wanna use flatpak?

**Comment by Eonfge** [comment] 2021-01-18 17:50
This is beyond the scope of this bugtracker, but let me try to help you.

Debian has a packaging system that relies on ._deb_ files, of on repositories which you can access using _apt_. Now, Debian is renown for their long term stability and it's reserved nature: It's not a fast driving sports car, it's an pickup. If you want Lollypop on Debian 10, you'll have to manually compile it or use Flatpak.

If you want a more middle-of-the-road Linux distribution, I would recommend Pop_OS or Linux Mint. If you want a more sports-capable distribution, consider Fedora or Suse Tumbleweed. At the time of writing, there are still a few Lollypop updates which I have to distribute, but I'm holding off now since Cedric had a few more bugs to fix.

May I ask,why don't you want to use Flatpak?

**Comment by linuxitomio** [comment] 2021-01-18 19:28
Thank you so much for your answer @eonfge. Part by part.  I am not a pro with computers and tech, but I like to try. I decide to use Debian cause is done for people all around the world. It looks in my eyes that is made out of love from people that are not just thinking about money but for the right of use tech. Maybe I got the idea wrong. So thats why I choose to use it , eventhough sometimes it can be more complex. Thats why Fedora seems to me a bit like a big company tryng to get more clients. BUt please, feel free to advise me about a distro that is has ethical like Debian and still can be a sport car. I love that methafores. thanks
And I dont use Flatpak, cause I just have so many problems with it. I still cant read the external device , eventhough I use a Flatpak installation.

**Comment by linuxitomio** [comment] 2021-01-18 19:53
And to say that this problem is using Flatpak

**Comment by Eonfge** [comment] 2021-01-18 20:19
Debian is certainly a community project, made with love and care by many dedicated contributors. What you could look into, is Debian Sid. Debian Sid is the latest version of Debian that gets updates on a fast cycle, which is then occasionally taken as the basis for a new long term release. It's the sports version of Debian, but it's also harder to drive.

That is a double edged sword though: Distributions who have a strong community focus, are also often more technical. Arch is famous for having a strong community, especially on the forums, but it's not accessible. Ubuntu is a very generic distribution, often used as people's first 'Linux' because it does enough right, but it lacks community. To go back to our cars comparison: a hatchback is easier to drive then a sports car.

I use Fedora myself, which is more like Red Hat employee's play garden. It combines the benefits of a strong corporate backer, with a community feeling. Fedora is state-of-the-art, often using new technologies before other distributions. Still, it's also quite principled: There is only FLOSS software in the official repository and they have a mission statement about [Freedom, Friends, Features and First](https://docs.fedoraproject.org/en-US/project/).

But well, it's a tough question. Perhaps you should just try a few things. Linux is about user choice and empowerment, and you should do what works for you. I used Ubuntu before, and I've also experimented with Suse Tumbleweed.

---

Related to Flatpak, your problems are mostly caused by Debian 10 I fear. You need Buster Backports to make everything work, and that is not the most reliable way of maintaining packages. What you could try, is the following:
```
flatpak override --user org.gnome.Lollypop --filesystem=host
```
This disables all sandboxing. It's not as secure as it could be, but it does allow you to test again. If it still doesn't work when you disable all sandboxing, then it's a different problem.

**Comment by linuxitomio** [comment] 2021-01-18 22:07
Waow. Thanks for your word.

I might say that I am using backports , but at some point while installing Lollypop  in flatpak version 1.8.5 through the backport, it suddenly says something about ayussass. I didnt understand that. So i have just uninstall Lollypop. Should I keep trying or I should just let it be then?

**Comment by Eonfge** [comment] 2021-01-19 15:44
That's apparently a known issue:
https://github.com/flatpak/flatpak/issues/3142

Can be caused by poor update processes, likely as a result of the backport.

---

The choice is yours. If you want to stick to Debian 10 and use Lollypop, then you have little choice besides Flathub. Else, you might want to try Debian Sid, or another distribution altogether.

**Comment by Eonfge** [comment] 2021-01-27 16:26
I'll close this issue unless you have further questions.  Feel free to reopen it then.

**Closed by Eonfge** 2021-01-27 16:26 UTC
